# Generated by Django 3.2.9 on 2024-09-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240822_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'компанию',
                'verbose_name_plural': 'компании',
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'роль', 'verbose_name_plural': 'роли'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователя', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
