# Generated by Django 3.2.9 on 2024-09-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20240911_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deep_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
