# Generated by Django 3.2.9 on 2024-09-11 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20240911_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Компания'),
        ),
    ]
